### PR TITLE
TB-2948 settings screen widgets

### PR DESCRIPTION
**Pull request by pro100svitlo**
### What 🕵️ 🔍

- create a list of settings-related widgets and data-models for them
- create a page in the example app with the settings-related widgets
- documentation and widget tests will be provided within the separate PR

----------

### How to test 🥼 🔬

- run the app
- compare figma-design with the cases displayed in the example app

----------

### Screenshots 📸 📱

| light | dark  |
| ------ | ------ |
|  |  |
|  |  |
|  |  |

----------

### References 📝 🔗

- [source name](https://xainag.atlassian.net/browse/TB-2948)
- [Figma](https://www.figma.com/file/8pOuL775gZljslS6b6nfJ5/Search-App-Design-%7C-Xayn?node-id=7564%3A9246)

----------

### CODE REVIEW

**Comment by peterstojanowski** [comment]
@pro100svitlo Can you please fix conflicts 🙂

**Comment by pro100svitlo** [comment]
> @pro100svitlo Can you please fix conflicts 🙂

sure. done 🏁

**Review by joecks — APPROVED** [review]
It looks good as it is. Just one question, are you still adding it to the example and Readme?

**Comment by pro100svitlo** [comment]
> It looks good as it is. Just one question, are you still adding it to the example and Readme?

Example app is done. You can try it  😉 
About docs: yes, within another task I am adding docs and widget tests.

**Pull request merged**
